# Generated by Django 4.1.3 on 2023-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('SE', 'Software Engineer'), ('PM', 'Product Manager'), ('DS', 'Data Scientist')], max_length=2)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(default='', max_length=30)),
                ('state', models.CharField(default='', help_text='Enter the State name', max_length=30)),
                ('country', models.CharField(default='', max_length=40)),
                ('zipcode', models.CharField(default='', help_text='Enter Zip code of Address', max_length=6)),
            ],
        ),
    ]
